apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/tejesvani/fraud-detection-platform/frontend:latest
          ports:
            - containerPort: 8501
              name: http
          envFrom:
            - configMapRef:
                name: fraud-detection-config
            - secretRef:
                name: fraud-detection-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
