apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-processor
  namespace: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-processor
  template:
    metadata:
      labels:
        app: risk-processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: risk-processor
          image: ghcr.io/tejesvani/fraud-detection-platform/risk-processor:latest
          ports:
            - containerPort: 8001
              name: metrics
          envFrom:
            - configMapRef:
                name: fraud-detection-config
            - secretRef:
                name: fraud-detection-secrets
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: risk-processor
  namespace: fraud-detection
spec:
  selector:
    app: risk-processor
  ports:
    - port: 8001
      targetPort: 8001
      name: metrics
