apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: fraud_detection_db
    user: ${POSTGRES_USER}
    uid: postgresql
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
